### ISSUE TITLE
Alpine Linux: Unable to create Virtual Network Adapter

### ISSUE THREAD

**Issue by GigaChad-Terminator** [SoftEtherVPN/SoftEtherVPN#1660]
### Prerequisites

* [ x] Can you reproduce?
* [ x] Are you running the latest version of SoftEtherVPN?

**SoftEther version:** master branch
**Component:** Client
**Operating system:** Alpine Linux v3.13.12 (container), Ubuntu 22.04.1 LTS (host machine)
**Architecture:** 64 bit

**Processor:** AMD Ryzen 9 3900x

### Description

Attempted to create a Virtual Network Adapter with the following command:
```
vpncmd /CLIENT localhost /CMD NicCreate vpn0
```
However, it fails to create one.

**Expected behavior:**
A Virtual Network Adapter to be successfully created.

**Actual behavior:**
Error occurred. (Error Code: 31)
Installation of the Virtual Network Adapter device driver failed.

### Steps to reproduce

1. Create a `Dockerfile` with the following content:
    ```
    ARG ALPINE_VERSION
    FROM alpine:${ALPINE_VERSION}
  
    ARG TZ
    RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone
    
    # Define environment variables
    ENV SOFTETHER_REPO https://github.com/SoftEtherVPN/SoftEtherVPN.git
    ENV S6_VERSION 2.2.0.3
    ENV USE_MUSL YES
    
    # Download s6 overlay
    ADD https://github.com/just-containers/s6-overlay/releases/download/v${S6_VERSION}/s6-overlay-amd64.tar.gz /tmp/
    
    # Install SoftEther VPN & s6 overlay
    RUN apk --no-cache update && \
        apk --no-cache upgrade && \
        apk --no-cache add bash && \
        # Install s6 supervisor
        tar xzf /tmp/s6-overlay-amd64.tar.gz -C / && \
        mkdir -p /etc/services.d && mkdir -p /etc/cont-init.d && mkdir -p /s6-bin && \
        # Install build dependencies
        apk --no-cache --virtual .build-deps add \
        git libgcc libstdc++ gcc musl-dev libc-dev g++ ncurses-dev \
        libsodium-dev readline-dev openssl-dev cmake make zlib-dev curl && \
        # Grab Softether from GitHub
        git clone ${SOFTETHER_REPO} /tmp/softether && \
        cd /tmp/softether && git fetch && git checkout master && git pull && git submodule init && git submodule update && \
        # Remove carriage returns
        find /tmp/softether -type f -print0 | xargs -0 dos2unix --
    
    # s6 behaviour
    ENV S6_KEEP_ENV 1
    ENV S6_BEHAVIOUR_IF_STAGE2_FAILS 2
    ENV S6_FIX_ATTRS_HIDDEN 1
    
    ENTRYPOINT ["/init"]
    ```
3. Create a `.env` file with the following content:
    ```
    # Common
    COMPOSE_PROJECT_NAME=test-project
    NETWORKS_DRIVER=bridge
    TIMEZONE=UTC
    
    # VPN
    ALPINE_VERSION=3.13
    ```
4. Create a `docker-compose.yml` file with the following content:
    ```
    version: "3.8"
    networks:
      frontend:
        driver: ${NETWORKS_DRIVER}
      backend:
        driver: ${NETWORKS_DRIVER}
    services:
      vpn:
        networks:
          - frontend
          - backend
        image: ${COMPOSE_PROJECT_NAME}_vpn:0.0.1
        build:
          context: ./
          args:
            - "ALPINE_VERSION=${ALPINE_VERSION}"
            - "TZ=${TIMEZONE}"
    ```
5. Build the vpn container:
    ```
    docker-compose build vpn
    ```
6. Up the vpn container:
    ```
    docker-compose up -d
    ```
7. Execute an interactive shell in the container
    ```
    docker-compose exec vpn bash
    ```
8. Build SoftEtherVPN
    ```
    cd /tmp/softether
    ./configure
    make -C build
    ```
9. Start the VPN Client
    ```
    cd /tmp/softether/build
    ./vpnclient start
    ```
10. Attempt to create the Virtual Network Adapter
    ```
    ./vpncmd /CLIENT localhost /CMD NicCreate vpn0
    ```
